// Deck information for Koma, Cosmos Serpent Commander
const sampleDeck = {
  name: "Jörmungandr, Dawn of Ragnarok",
  colors: ["U", "G"],
  format: "Commander",
  strategy:
    "This Simic deck focuses on token generation and cloning effects to create an overwhelming board presence. The strategy revolves around generating serpent tokens with Koma and then multiplying them through various doubling effects and clone spells.",
  commander: "Koma, Cosmos Serpent",
  cards: [
    {
      id: 1,
      name: "Adrix and Nev, Twincasters",
      type: "Legendary Creature",
      manaCost: 4,
      colors: ["U", "G"],
      role: "Token Doubler",
    },
    {
      id: 2,
      name: "Aesi, Tyrant of Gyre Strait",
      type: "Legendary Creature",
      manaCost: 5,
      colors: ["U", "G"],
      role: "Draw Engine",
    },
    {
      id: 3,
      name: "An Offer You Can't Refuse",
      type: "Instant",
      manaCost: 1,
      colors: ["U"],
      role: "Protection",
    },
    {
      id: 4,
      name: "Ancient Greenwarden",
      type: "Creature",
      manaCost: 6,
      colors: ["G"],
      role: "Recursion",
    },
    {
      id: 5,
      name: "Arcane Adaptation",
      type: "Enchantment",
      manaCost: 3,
      colors: ["U"],
      role: "Tribal Support",
    },
    {
      id: 6,
      name: "Arcane Signet",
      type: "Artifact",
      manaCost: 2,
      colors: [],
      role: "Ramp",
    },
    {
      id: 7,
      name: "Archetype of Imagination",
      type: "Enchantment Creature",
      manaCost: 6,
      colors: ["U"],
      role: "Evasion",
    },
    {
      id: 8,
      name: "Arixmethes, Slumbering Isle",
      type: "Legendary Creature",
      manaCost: 4,
      colors: ["U", "G"],
      role: "Ramp",
    },
    {
      id: 9,
      name: "Asceticism",
      type: "Enchantment",
      manaCost: 5,
      colors: ["G"],
      role: "Protection",
    },
    {
      id: 10,
      name: "Auroral Procession",
      type: "Enchantment",
      manaCost: 4,
      colors: ["U"],
      role: "Cloning",
    },
    {
      id: 11,
      name: "Shifting Woodland",
      type: "Land",
      manaCost: 0,
      colors: ["G"],
      role: "Lands",
    },
    {
      id: 12,
      name: "Banner of Kinship",
      type: "Artifact",
      manaCost: 5,
      colors: [],
      role: "Tribal Support",
    },
    {
      id: 13,
      name: "Boseiju, Who Endures",
      type: "Legendary Land",
      manaCost: 0,
      colors: ["G"],
      role: "Lands",
    },
    {
      id: 14,
      name: "Broken Bond",
      type: "Sorcery",
      manaCost: 2,
      colors: ["G"],
      role: "Removal",
    },
    {
      id: 15,
      name: "Burgeoning",
      type: "Enchantment",
      manaCost: 1,
      colors: ["G"],
      role: "Ramp",
    },
    {
      id: 16,
      name: "Castle Garenbrig",
      type: "Land",
      manaCost: 0,
      colors: ["G"],
      role: "Lands",
    },
    {
      id: 17,
      name: "Command Beacon",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Lands",
    },
    {
      id: 18,
      name: "Command Tower",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Lands",
    },
    {
      id: 19,
      name: "Craterhoof Behemoth",
      type: "Creature",
      manaCost: 8,
      colors: ["G"],
      role: "Gamechanger",
    },
    {
      id: 20,
      name: "Cultivate",
      type: "Sorcery",
      manaCost: 3,
      colors: ["G"],
      role: "Ramp",
    },
    {
      id: 21,
      name: "Cyclonic Rift",
      type: "Instant",
      manaCost: 2,
      colors: ["U"],
      role: "Removal",
    },
    {
      id: 22,
      name: "Decanter of Endless Water",
      type: "Artifact",
      manaCost: 3,
      colors: [],
      role: "Ramp",
    },
    {
      id: 23,
      name: "Defense of the Heart",
      type: "Enchantment",
      manaCost: 3,
      colors: ["G"],
      role: "Tutor",
    },
    {
      id: 24,
      name: "Delighted Halfling",
      type: "Creature",
      manaCost: 1,
      colors: ["G"],
      role: "Ramp",
    },
    {
      id: 25,
      name: "Double Major",
      type: "Sorcery",
      manaCost: 4,
      colors: ["U"],
      role: "Cloning",
    },
    {
      id: 26,
      name: "Doubling Season",
      type: "Enchantment",
      manaCost: 5,
      colors: ["G"],
      role: "Token Doubler",
    },
    {
      id: 27,
      name: "Eldrazi Monument",
      type: "Artifact",
      manaCost: 5,
      colors: [],
      role: "Protection",
    },
    {
      id: 28,
      name: "Enduring Vitality",
      type: "Enchantment",
      manaCost: 2,
      colors: ["G"],
      role: "Value Engine",
    },
    {
      id: 29,
      name: "Esix, Fractal Bloom",
      type: "Legendary Creature",
      manaCost: 4,
      colors: ["U", "G"],
      role: "Cloning",
    },
    {
      id: 30,
      name: "Eternal Witness",
      type: "Creature",
      manaCost: 3,
      colors: ["G"],
      role: "Recursion",
    },
    {
      id: 31,
      name: "Evolving Wilds",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Lands",
    },
    {
      id: 32,
      name: "Explosive Vegetation",
      type: "Sorcery",
      manaCost: 4,
      colors: ["G"],
      role: "Ramp",
    },
    {
      id: 33,
      name: "Fabled Passage",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Lands",
    },
    {
      id: 34,
      name: "Fanatic of Rhonas",
      type: "Creature",
      manaCost: 2,
      colors: ["G"],
      role: "Ramp",
    },
    {
      id: 35,
      name: "Fierce Guardianship",
      type: "Instant",
      manaCost: 3,
      colors: ["U"],
      role: "Protection",
    },
    {
      id: 36,
      name: "Forest",
      type: "Basic Land",
      manaCost: 0,
      colors: ["G"],
      role: "Lands",
    },
    {
      id: 37,
      name: "Garruk's Uprising",
      type: "Enchantment",
      manaCost: 3,
      colors: ["G"],
      role: "Draw Engine",
    },
    {
      id: 38,
      name: "Nyxbloom Ancient",
      type: "Enchantment Creature",
      manaCost: 7,
      colors: ["G"],
      role: "Ramp",
    },
    {
      id: 39,
      name: "Helm of the Host",
      type: "Legendary Artifact",
      manaCost: 4,
      colors: [],
      role: "Cloning",
    },
    {
      id: 40,
      name: "Heroic Intervention",
      type: "Instant",
      manaCost: 2,
      colors: ["G"],
      role: "Protection",
    },
    {
      id: 41,
      name: "Hinterland Harbor",
      type: "Land",
      manaCost: 0,
      colors: ["U", "G"],
      role: "Lands",
    },
    {
      id: 42,
      name: "Imprisoned in the Moon",
      type: "Enchantment",
      manaCost: 3,
      colors: ["U"],
      role: "Removal",
    },
    {
      id: 43,
      name: "Irenicus's Vile Duplication",
      type: "Sorcery",
      manaCost: 3,
      colors: ["U"],
      role: "Cloning",
    },
    {
      id: 44,
      name: "Island",
      type: "Basic Land",
      manaCost: 0,
      colors: ["U"],
      role: "Lands",
    },
    {
      id: 45,
      name: "Jaheira, Friend of the Forest",
      type: "Legendary Creature",
      manaCost: 2,
      colors: ["G"],
      role: "Ramp",
    },
    {
      id: 46,
      name: "Junk Winder",
      type: "Creature",
      manaCost: 5,
      colors: ["U"],
      role: "Removal",
    },
    {
      id: 47,
      name: "Kodama's Reach",
      type: "Sorcery",
      manaCost: 3,
      colors: ["G"],
      role: "Ramp",
    },
    {
      id: 48,
      name: "Koma, Cosmos Serpent",
      type: "Legendary Creature",
      manaCost: 7,
      colors: ["U", "G"],
      role: "Commander",
    },
    {
      id: 49,
      name: "Koma, World-Eater",
      type: "Legendary Creature",
      manaCost: 6,
      colors: ["U", "G"],
      role: "Cloning",
    },
    {
      id: 50,
      name: "Last March of the Ents",
      type: "Sorcery",
      manaCost: 6,
      colors: ["G"],
      role: "Token Generator",
    },
    {
      id: 51,
      name: "Migration Path",
      type: "Sorcery",
      manaCost: 4,
      colors: ["G"],
      role: "Ramp",
    },
    {
      id: 52,
      name: "Mirror Box",
      type: "Artifact",
      manaCost: 3,
      colors: [],
      role: "Tribal Support",
    },
    {
      id: 53,
      name: "Mistrise Village",
      type: "Land",
      manaCost: 0,
      colors: ["U"],
      role: "Lands",
    },
    {
      id: 54,
      name: "Mosswort Bridge",
      type: "Land",
      manaCost: 0,
      colors: ["G"],
      role: "Lands",
    },
    {
      id: 55,
      name: "Murkfiend Liege",
      type: "Creature",
      manaCost: 5,
      colors: ["U", "G"],
      role: "Value Engine",
    },
    {
      id: 56,
      name: "Myriad Landscape",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Lands",
    },
    {
      id: 57,
      name: "Mystic Reflection",
      type: "Instant",
      manaCost: 2,
      colors: ["U"],
      role: "Cloning",
    },
    {
      id: 58,
      name: "Nature's Lore",
      type: "Sorcery",
      manaCost: 2,
      colors: ["G"],
      role: "Ramp",
    },
    {
      id: 59,
      name: "Ohran Frostfang",
      type: "Creature",
      manaCost: 4,
      colors: ["G"],
      role: "Draw Engine",
    },
    {
      id: 60,
      name: "Otawara, Soaring City",
      type: "Legendary Land",
      manaCost: 0,
      colors: ["U"],
      role: "Lands",
    },
    {
      id: 61,
      name: "Propaganda",
      type: "Enchantment",
      manaCost: 3,
      colors: ["U"],
      role: "Protection",
    },
    {
      id: 62,
      name: "Rampant Growth",
      type: "Sorcery",
      manaCost: 2,
      colors: ["G"],
      role: "Ramp",
    },
    {
      id: 63,
      name: "Rejuvenating Springs",
      type: "Land",
      manaCost: 0,
      colors: ["U", "G"],
      role: "Lands",
    },
    {
      id: 64,
      name: "Reliquary Tower",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Lands",
    },
    {
      id: 65,
      name: "Rhystic Study",
      type: "Enchantment",
      manaCost: 3,
      colors: ["U"],
      role: "Draw Engine",
    },
    {
      id: 66,
      name: "Roaming Throne",
      type: "Artifact Creature",
      manaCost: 4,
      colors: [],
      role: "Tribal Support",
    },
    {
      id: 67,
      name: "Sakashima of a Thousand Faces",
      type: "Legendary Creature",
      manaCost: 4,
      colors: ["U"],
      role: "Cloning",
    },
    {
      id: 68,
      name: "Scute Swarm",
      type: "Creature",
      manaCost: 3,
      colors: ["G"],
      role: "Token Generator",
    },
    {
      id: 69,
      name: "Second Harvest",
      type: "Instant",
      manaCost: 3,
      colors: ["G"],
      role: "Token Doubler",
    },
    {
      id: 70,
      name: "Seedborn Muse",
      type: "Creature",
      manaCost: 5,
      colors: ["G"],
      role: "Value Engine",
    },
    {
      id: 71,
      name: "Serpent of Yawning Depths",
      type: "Creature",
      manaCost: 7,
      colors: ["U"],
      role: "Threat",
    },
    {
      id: 72,
      name: "Simic Growth Chamber",
      type: "Land",
      manaCost: 0,
      colors: ["U", "G"],
      role: "Lands",
    },
    {
      id: 73,
      name: "Skyshroud Claim",
      type: "Sorcery",
      manaCost: 4,
      colors: ["G"],
      role: "Ramp",
    },
    {
      id: 74,
      name: "Sol Ring",
      type: "Artifact",
      manaCost: 1,
      colors: [],
      role: "Ramp",
    },
    {
      id: 75,
      name: "Spark Double",
      type: "Creature",
      manaCost: 4,
      colors: ["U"],
      role: "Cloning",
    },
    {
      id: 76,
      name: "Spawning Kraken",
      type: "Creature",
      manaCost: 6,
      colors: ["U"],
      role: "Token Generator",
    },
    {
      id: 77,
      name: "Stubborn Denial",
      type: "Instant",
      manaCost: 1,
      colors: ["U"],
      role: "Protection",
    },
    {
      id: 78,
      name: "Tatyova, Benthic Druid",
      type: "Legendary Creature",
      manaCost: 5,
      colors: ["U", "G"],
      role: "Draw Engine",
    },
    {
      id: 79,
      name: "Temple of the False God",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Lands",
    },
    {
      id: 80,
      name: "Terramorphic Expanse",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Lands",
    },
    {
      id: 81,
      name: "The Great Henge",
      type: "Legendary Artifact",
      manaCost: 9,
      colors: [],
      role: "Value Engine",
    },
    {
      id: 82,
      name: "Three Tree City",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Lands",
    },
    {
      id: 83,
      name: "Tropical Island",
      type: "Land",
      manaCost: 0,
      colors: ["U", "G"],
      role: "Lands",
    },
    {
      id: 84,
      name: "Verdant Sun's Avatar",
      type: "Creature",
      manaCost: 7,
      colors: ["G"],
      role: "Threat",
    },
    {
      id: 85,
      name: "Vineglimmer Snarl",
      type: "Land",
      manaCost: 0,
      colors: ["U", "G"],
      role: "Lands",
    },
    {
      id: 86,
      name: "Whelming Wave",
      type: "Sorcery",
      manaCost: 4,
      colors: ["U"],
      role: "Removal",
    },
    {
      id: 87,
      name: "Wonder",
      type: "Creature",
      manaCost: 4,
      colors: ["U"],
      role: "Evasion",
    },
    {
      id: 88,
      name: "Worldly Tutor",
      type: "Instant",
      manaCost: 1,
      colors: ["G"],
      role: "Tutor",
    },
    {
      id: 89,
      name: "Yavimaya, Cradle of Growth",
      type: "Legendary Land",
      manaCost: 0,
      colors: ["G"],
      role: "Lands",
    },
  ],
}

// Export the deck data
export default sampleDeck
