// Deck information for Koma, Cosmos Serpent Commander
const sampleDeck = {
  name: "Koma Kage Bunshin no Jutsu",
  colors: ["U", "G"],
  format: "Commander",
  strategy:
    "This Simic deck creates an unstoppable army of serpent tokens with Koma, Cosmos Serpent at the helm. Generate tokens every upkeep, protect your board, and overwhelm opponents with a sea of serpents.",
  commander: "Koma, Cosmos Serpent",
  cards: [
    {
      id: 1,
      name: "Adrix and Nev, Twincasters",
      type: "Legendary Creature",
      manaCost: 4,
      colors: ["U", "G"],
      role: "Doubles the number of tokens you create",
    },
    {
      id: 2,
      name: "Aesi, Tyrant of Gyre Strait",
      type: "Legendary Creature",
      manaCost: 5,
      colors: ["U", "G"],
      role: "Provides card draw and extra land drops",
    },
    {
      id: 3,
      name: "An Offer You Can't Refuse",
      type: "Instant",
      manaCost: 1,
      colors: ["U"],
      role: "Cheap counterspell with minor drawback",
    },
    {
      id: 4,
      name: "Ancient Greenwarden",
      type: "Creature",
      manaCost: 6,
      colors: ["G"],
      role: "Landfall value engine and graveyard recursion",
    },
    {
      id: 5,
      name: "Arcane Adaptation",
      type: "Enchantment",
      manaCost: 3,
      colors: ["U"],
      role: "Makes all creatures share a creature type",
    },
    {
      id: 6,
      name: "Arcane Signet",
      type: "Artifact",
      manaCost: 2,
      colors: [],
      role: "Mana rock that produces commander colors",
    },
    {
      id: 7,
      name: "Archetype of Imagination",
      type: "Enchantment Creature",
      manaCost: 6,
      colors: ["U"],
      role: "Gives all creatures flying and removes flying from opponents",
    },
    {
      id: 8,
      name: "Arixmethes, Slumbering Isle",
      type: "Legendary Creature",
      manaCost: 4,
      colors: ["U", "G"],
      role: "Mana dork that becomes a massive creature",
    },
    {
      id: 9,
      name: "Asceticism",
      type: "Enchantment",
      manaCost: 5,
      colors: ["G"],
      role: "Protects creatures from targeted removal",
    },
    {
      id: 10,
      name: "Auroral Procession",
      type: "Enchantment",
      manaCost: 4,
      colors: ["U"],
      role: "Creates token copies of creatures",
    },
    {
      id: 11,
      name: "Shifting Woodland",
      type: "Land",
      manaCost: 0,
      colors: ["G"],
      role: "Copies a card from your graveyard",
    },
    {
      id: 12,
      name: "Banner of Kinship",
      type: "Artifact",
      manaCost: 5,
      colors: [],
      role: "Tribal support and token creation",
    },
    {
      id: 13,
      name: "Boseiju, Who Endures",
      type: "Legendary Land",
      manaCost: 0,
      colors: ["G"],
      role: "Utility land with artifact/enchantment removal",
    },
    {
      id: 14,
      name: "Broken Bond",
      type: "Sorcery",
      manaCost: 2,
      colors: ["G"],
      role: "Destroys artifact or enchantment and ramps",
    },
    {
      id: 15,
      name: "Burgeoning",
      type: "Enchantment",
      manaCost: 1,
      colors: ["G"],
      role: "Accelerates land drops on opponents' turns",
    },
    {
      id: 16,
      name: "Castle Garenbrig",
      type: "Land",
      manaCost: 0,
      colors: ["G"],
      role: "Utility land that produces extra mana for creatures",
    },
    {
      id: 17,
      name: "Command Beacon",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Puts commander into hand to avoid commander tax",
    },
    {
      id: 18,
      name: "Command Tower",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Perfect mana fixing for commander colors",
    },
    {
      id: 19,
      name: "Craterhoof Behemoth",
      type: "Creature",
      manaCost: 8,
      colors: ["G"],
      role: "Game-ending finisher that buffs all creatures",
    },
    {
      id: 20,
      name: "Cultivate",
      type: "Sorcery",
      manaCost: 3,
      colors: ["G"],
      role: "Ramp spell that fetches two lands",
    },
    {
      id: 21,
      name: "Cyclonic Rift",
      type: "Instant",
      manaCost: 2,
      colors: ["U"],
      role: "Bounce spell with powerful overload option",
    },
    {
      id: 22,
      name: "Decanter of Endless Water",
      type: "Artifact",
      manaCost: 3,
      colors: [],
      role: "Mana rock with card draw potential",
    },
    {
      id: 23,
      name: "Defense of the Heart",
      type: "Enchantment",
      manaCost: 3,
      colors: ["G"],
      role: "Tutors two creatures when opponents have many creatures",
    },
    {
      id: 24,
      name: "Delighted Halfling",
      type: "Creature",
      manaCost: 1,
      colors: ["G"],
      role: "Mana dork that makes legendary spells uncounterable",
    },
    {
      id: 25,
      name: "Double Major",
      type: "Sorcery",
      manaCost: 4,
      colors: ["U"],
      role: "Creates a token copy of a creature",
    },
    {
      id: 26,
      name: "Doubling Season",
      type: "Enchantment",
      manaCost: 5,
      colors: ["G"],
      role: "Doubles tokens and counters",
    },
    {
      id: 27,
      name: "Eldrazi Monument",
      type: "Artifact",
      manaCost: 5,
      colors: [],
      role: "Makes creatures indestructible and flying",
    },
    {
      id: 28,
      name: "Enduring Vitality",
      type: "Enchantment",
      manaCost: 2,
      colors: ["G"],
      role: "Provides life gain and creature buffs",
    },
    {
      id: 29,
      name: "Esix, Fractal Bloom",
      type: "Legendary Creature",
      manaCost: 4,
      colors: ["U", "G"],
      role: "Turns token creation into copying other creatures",
    },
    {
      id: 30,
      name: "Eternal Witness",
      type: "Creature",
      manaCost: 3,
      colors: ["G"],
      role: "Returns card from graveyard to hand",
    },
    {
      id: 31,
      name: "Evolving Wilds",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Fetch land for basic lands",
    },
    {
      id: 32,
      name: "Explosive Vegetation",
      type: "Sorcery",
      manaCost: 4,
      colors: ["G"],
      role: "Ramp spell that puts two lands into play",
    },
    {
      id: 33,
      name: "Fabled Passage",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Fetch land that enters untapped later",
    },
    {
      id: 34,
      name: "Fanatic of Rhonas",
      type: "Creature",
      manaCost: 2,
      colors: ["G"],
      role: "Mana dork with eternalize ability",
    },
    {
      id: 35,
      name: "Fierce Guardianship",
      type: "Instant",
      manaCost: 3,
      colors: ["U"],
      role: "Free counterspell if you control your commander",
    },
    {
      id: 36,
      name: "Forest",
      type: "Basic Land",
      manaCost: 0,
      colors: ["G"],
      role: "Basic green mana source",
    },
    {
      id: 37,
      name: "Garruk's Uprising",
      type: "Enchantment",
      manaCost: 3,
      colors: ["G"],
      role: "Draws cards for large creatures and gives trample",
    },
    {
      id: 38,
      name: "Nyxbloom Ancient",
      type: "Enchantment Creature",
      manaCost: 3,
      colors: ["G"],
      role: "Triples mana generation from permanents",
    },
    {
      id: 39,
      name: "Helm of the Host",
      type: "Legendary Artifact",
      manaCost: 4,
      colors: [],
      role: "Creates token copies of equipped creature",
    },
    {
      id: 40,
      name: "Heroic Intervention",
      type: "Instant",
      manaCost: 2,
      colors: ["G"],
      role: "Protects permanents from removal",
    },
    {
      id: 41,
      name: "Hinterland Harbor",
      type: "Land",
      manaCost: 0,
      colors: ["U", "G"],
      role: "Dual land that enters untapped with basics",
    },
    {
      id: 42,
      name: "Imprisoned in the Moon",
      type: "Enchantment",
      manaCost: 3,
      colors: ["U"],
      role: "Neutralizes problematic permanents",
    },
    {
      id: 43,
      name: "Irenicus's Vile Duplication",
      type: "Sorcery",
      manaCost: 3,
      colors: ["U"],
      role: "Creates token copy and gives it to opponent",
    },
    {
      id: 44,
      name: "Island",
      type: "Basic Land",
      manaCost: 0,
      colors: ["U"],
      role: "Basic blue mana source",
    },
    {
      id: 45,
      name: "Jaheira, Friend of the Forest",
      type: "Legendary Creature",
      manaCost: 2,
      colors: ["G"],
      role: "Makes tokens into mana dorks",
    },
    {
      id: 46,
      name: "Junk Winder",
      type: "Creature",
      manaCost: 5,
      colors: ["U"],
      role: "Taps artifacts and draws cards",
    },
    {
      id: 47,
      name: "Kodama's Reach",
      type: "Sorcery",
      manaCost: 3,
      colors: ["G"],
      role: "Ramp spell similar to Cultivate",
    },
    {
      id: 48,
      name: "Koma, Cosmos Serpent",
      type: "Legendary Creature",
      manaCost: 7,
      colors: ["U", "G"],
      role: "Commander that creates serpent tokens",
    },
    {
      id: 49,
      name: "Koma, World-Eater",
      type: "Legendary Creature",
      manaCost: 6,
      colors: ["U", "G"],
      role: "Alternative Koma with different abilities",
    },
    {
      id: 50,
      name: "Last March of the Ents",
      type: "Sorcery",
      manaCost: 6,
      colors: ["G"],
      role: "Mass creature token creation",
    },
    {
      id: 51,
      name: "Migration Path",
      type: "Sorcery",
      manaCost: 4,
      colors: ["G"],
      role: "Ramp spell with cycling option",
    },
    {
      id: 52,
      name: "Mirror Box",
      type: "Artifact",
      manaCost: 3,
      colors: [],
      role: "Allows multiple legendary creatures",
    },
    {
      id: 53,
      name: "Mistrise Village",
      type: "Land",
      manaCost: 0,
      colors: ["U"],
      role: "Utility land with creature creation",
    },
    {
      id: 54,
      name: "Mosswort Bridge",
      type: "Land",
      manaCost: 0,
      colors: ["G"],
      role: "Hideaway land for free spells",
    },
    {
      id: 55,
      name: "Murkfiend Liege",
      type: "Creature",
      manaCost: 5,
      colors: ["U", "G"],
      role: "Untaps creatures and buffs them",
    },
    {
      id: 56,
      name: "Myriad Landscape",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Utility land that fetches basic lands",
    },
    {
      id: 57,
      name: "Mystic Reflection",
      type: "Instant",
      manaCost: 2,
      colors: ["U"],
      role: "Makes creatures enter as copies of target",
    },
    {
      id: 58,
      name: "Nature's Lore",
      type: "Sorcery",
      manaCost: 2,
      colors: ["G"],
      role: "Ramp spell that gets Forest into play",
    },
    {
      id: 59,
      name: "Ohran Frostfang",
      type: "Creature",
      manaCost: 4,
      colors: ["G"],
      role: "Gives creatures deathtouch and card draw",
    },
    {
      id: 60,
      name: "Otawara, Soaring City",
      type: "Legendary Land",
      manaCost: 0,
      colors: ["U"],
      role: "Utility land with bounce effect",
    },
    {
      id: 61,
      name: "Propaganda",
      type: "Enchantment",
      manaCost: 3,
      colors: ["U"],
      role: "Taxes opponents for attacking you",
    },
    {
      id: 62,
      name: "Rampant Growth",
      type: "Sorcery",
      manaCost: 2,
      colors: ["G"],
      role: "Basic ramp spell",
    },
    {
      id: 63,
      name: "Rejuvenating Springs",
      type: "Land",
      manaCost: 0,
      colors: ["U", "G"],
      role: "Dual land that enters untapped in multiplayer",
    },
    {
      id: 64,
      name: "Reliquary Tower",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Removes maximum hand size",
    },
    {
      id: 65,
      name: "Rhystic Study",
      type: "Enchantment",
      manaCost: 3,
      colors: ["U"],
      role: "Powerful card draw engine",
    },
    {
      id: 66,
      name: "Roaming Throne",
      type: "Artifact Creature",
      manaCost: 4,
      colors: [],
      role: "Doubles triggered abilities of chosen creature type",
    },
    {
      id: 67,
      name: "Sakashima of a Thousand Faces",
      type: "Legendary Creature",
      manaCost: 4,
      colors: ["U"],
      role: "Clone that can copy legendary creatures",
    },
    {
      id: 68,
      name: "Scute Swarm",
      type: "Creature",
      manaCost: 3,
      colors: ["G"],
      role: "Creates token copies with landfall",
    },
    {
      id: 69,
      name: "Second Harvest",
      type: "Instant",
      manaCost: 3,
      colors: ["G"],
      role: "Doubles all tokens you control",
    },
    {
      id: 70,
      name: "Seedborn Muse",
      type: "Creature",
      manaCost: 5,
      colors: ["G"],
      role: "Untaps permanents on each opponent's turn",
    },
    {
      id: 71,
      name: "Serpent of Yawning Depths",
      type: "Creature",
      manaCost: 7,
      colors: ["U"],
      role: "Large serpent with kicker ability",
    },
    {
      id: 72,
      name: "Simic Growth Chamber",
      type: "Land",
      manaCost: 0,
      colors: ["U", "G"],
      role: "Bounce land that produces two mana",
    },
    {
      id: 73,
      name: "Skyshroud Claim",
      type: "Sorcery",
      manaCost: 4,
      colors: ["G"],
      role: "Ramp spell that gets Forests into play untapped",
    },
    {
      id: 74,
      name: "Sol Ring",
      type: "Artifact",
      manaCost: 1,
      colors: [],
      role: "Fast mana acceleration",
    },
    {
      id: 75,
      name: "Spark Double",
      type: "Creature",
      manaCost: 4,
      colors: ["U"],
      role: "Clone that can copy planeswalkers and legendaries",
    },
    {
      id: 76,
      name: "Spawning Kraken",
      type: "Creature",
      manaCost: 6,
      colors: ["U"],
      role: "Creates tokens when attacking with large creatures",
    },
    {
      id: 77,
      name: "Stubborn Denial",
      type: "Instant",
      manaCost: 1,
      colors: ["U"],
      role: "Cheap counterspell with ferocious upside",
    },
    {
      id: 78,
      name: "Tatyova, Benthic Druid",
      type: "Legendary Creature",
      manaCost: 5,
      colors: ["U", "G"],
      role: "Draws cards and gains life from landfall",
    },
    {
      id: 79,
      name: "Temple of the False God",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Produces two mana if you have enough lands",
    },
    {
      id: 80,
      name: "Terramorphic Expanse",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Fetch land for basic lands",
    },
    {
      id: 81,
      name: "The Great Henge",
      type: "Legendary Artifact",
      manaCost: 9,
      colors: [],
      role: "Powerful value engine that costs less with creatures",
    },
    {
      id: 82,
      name: "Three Tree City",
      type: "Land",
      manaCost: 0,
      colors: [],
      role: "Utility land with creature type synergies",
    },
    {
      id: 83,
      name: "Tropical Island",
      type: "Land",
      manaCost: 0,
      colors: ["U", "G"],
      role: "Original dual land with no drawbacks",
    },
    {
      id: 84,
      name: "Verdant Sun's Avatar",
      type: "Creature",
      manaCost: 7,
      colors: ["G"],
      role: "Large creature that gains life equal to its power",
    },
    {
      id: 85,
      name: "Vineglimmer Snarl",
      type: "Land",
      manaCost: 0,
      colors: ["U", "G"],
      role: "Dual land that enters untapped with spell condition",
    },
    {
      id: 86,
      name: "Whelming Wave",
      type: "Sorcery",
      manaCost: 4,
      colors: ["U"],
      role: "Mass bounce spell that spares large creatures",
    },
    {
      id: 87,
      name: "Wonder",
      type: "Creature",
      manaCost: 4,
      colors: ["U"],
      role: "Gives all creatures flying from graveyard",
    },
    {
      id: 88,
      name: "Worldly Tutor",
      type: "Instant",
      manaCost: 1,
      colors: ["G"],
      role: "Tutors creature to top of library",
    },
    {
      id: 89,
      name: "Yavimaya, Cradle of Growth",
      type: "Legendary Land",
      manaCost: 0,
      colors: ["G"],
      role: "Makes all lands into Forests",
    },
  ],
}

// Export the deck data
export default sampleDeck
